# Generated by Django 4.2 on 2024-09-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgpt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('stars', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
