# Generated by Django 4.2 on 2024-10-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgpt_app', '0003_question_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
