# Generated by Django 4.2 on 2024-10-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csgpt_app', '0005_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
