# Generated by Django 4.2 on 2024-10-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgpt_app', '0007_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_of_question',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
