# Generated by Django 4.2 on 2024-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgpt_app', '0009_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_of_question',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
